Models/ErrorViewModel.cs
using System;

namespace pokedex.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pokemon.cs
namespace pokedex.Models
{
    public class Pokemon
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Foto { get; set; }

         public string Maestro { get; set; }
        public string Lugar { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using pokedex.Models;

namespace pokedex.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PokemonController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using pokedex.Data;
using pokedex.Models;

namespace pokedex.Controllers
{
    public class PokemonController : Controller
    {
        private PokedexContext _context;
        public PokemonController(PokedexContext context)
        {
            _context = context;
        }

        public IActionResult Nuevo() {
            return View();
        }

        [HttpPost]
        public IActionResult Nuevo(Pokemon p) {
            if (ModelState.IsValid) {
                // Guardar el objeto Pokemon (p)
                _context.Add(p);
                _context.SaveChanges();
                
                return RedirectToAction("Lista");
            }
            
            return View(p);
        }

        public IActionResult Lista() {
            var pokemones = _context.Pokemones.OrderBy(x => x.Nombre).ToList();
            return View(pokemones);
        }

          public IActionResult Registro() {
            return View();
        }

        [HttpPost]
       
       

        public IActionResult Registro(Pokemon r)
         {
             if (ModelState.IsValid) {
                // Guardar el objeto Pokemon (p)
                _context.Add(r);
                _context.SaveChanges();
                
                return RedirectToAction("Registro");
            }
            
            return View(r);

         }

         public IActionResult ListaCiudades() {
            var pokemones = _context.Pokemones.OrderBy(x => x.Nombre).ToList();
            return View(pokemones);
         }

         
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Pokemon/Lista.cshtml
@model List<Pokemon>

<h1>Lista de pokemones registrados en la Pokedex</h1>

@if (Model.Count == 0) {
    <div class="alert alert-warning text-center">Aún no hay pokemones en la pokedex.</div>
} else {
    <ol>
    @foreach (var p in Model) {
        <li class="d-flex">
            <div><img src="@p.Foto" /></div>
            <div>@p.Nombre</div>
        </li>
    }
    </ol>
}

Views/Pokemon/ListaCiudades.cshtml
@model List<Pokemon>

<h1>Lista de Ciudades registradas en la Pokedex</h1>

@if (Model.Count == 0) {
    <div class="alert alert-warning text-center">Aún no hay Ciudades registradas.</div>
} else {
    <ol>
    @foreach (var r in Model) {
        <li class="d-flex">
            <div><img src="@r.Maestro" /></div>
            <div>@r.Lugar</div>
        </li>
    }
    </ol>
}

Views/Pokemon/Nuevo.cshtml
@model Pokemon

<h1>Ingresar Pokemon</h1>

<form method="post">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Foto"></label>
        <input asp-for="Foto" class="form-control">
    </div>
    <button class="btn btn-primary">Enviar</button>
</form>

Views/Pokemon/Registro.cshtml
@model Pokemon

<h1>Registrar Ciudades</h1>

<form method="post">
    <div class="form-group">
        <label asp-for="Lugar"></label>
        <input asp-for="Lugar" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Maestro"></label>
        <input asp-for="Maestro" class="form-control">
    </div>
    <button class="btn btn-primary">Enviar</button>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - pokedex</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">pokedex</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Pokemon" asp-action="Nuevo">Añadir Pokemon</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Pokemon" asp-action="Lista">Lista de Pokemon</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Pokemon" asp-action="Registro">Añadir Ciudades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Pokemon" asp-action="ListaCiudades">Lista de Ciudades</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - pokedex - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>